import pytest
from app import app, init_db


@pytest.fixture
def client():
    app.config["TESTING"] = True

    # Make sure the database table exists
    init_db()

    with app.test_client() as client:
        yield client


def test_home_page(client):
    response = client.get("/")

    assert response.status_code == 200
    assert b"Job Application Tracker" in response.data